version: '3.0'

services:

  server:
    image: app_server
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    depends_on:
      - database
    networks:
      - custom_user_network

  database:
    image: postgres_database
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 
    networks:
      - custom_user_network

networks:
  custom_user_network:
    driver: bridge
