config:
  target: 'http://localhost:4000'
  phases:
    - duration: 30
      arrivalRate: 5
      name: Warm up
    - duration: 60
      arrivalRate: 5
      rampTo: 20
      name: Ramp up load
    - duration: 120
      arrivalRate: 20
      name: Sustained load
before:
  flow:
    - log: 'Get token'
    - post:
        url: '/login'
        json:
          login: 'admin'
          password: 'admin'
        capture:
          - json: $.token
            as: token
scenarios:
  - name: 'User'
    flow:
      - post:
          url: '/users'
          headers:
            authorization: 'Bearer {{ token }}'
          json:
            name: 'user1'
            login: 'user2'
            password: 'user3'
          capture:
            json: $.id
            as: userID
          expect:
            - statusCode: 201
      - get:
          url: '/users'
          headers:
            authorization: 'Bearer {{ token }}'
          expect:
            - statusCode: 200
      - put:
          url: '/users/{{ userID }}'
          headers:
            authorization: 'Bearer {{ token }}'
          json:
            name: 'user4'
            login: 'user5'
            password: 'user6'
          expect:
            - statusCode: 200
      - get:
          url: '/users/{{ userID }}'
          headers:
            authorization: 'Bearer {{ token }}'
          expect:
            - statusCode: 200
      - delete:
          url: '/users/{{ userID }}'
          headers:
            authorization: 'Bearer {{ token }}'
          expect:
            - statusCode: 204
